### ISSUE TITLE
SSL certitificate issue. 

### ISSUE THREAD

**Issue by NoahWhite1115** [NoahWhite1115/Funnies#10]
When run on windows, many sites respond with SSL errors. This does not occur on linux. I'm not sure as to the exact nature of the issue, but I'll add info here as I do more research.

**Comment by NoahWhite1115** [comment]
Here's the specific error.

Traceback (most recent call last):
  File "AddToFunnies.py", line 164, in <module>
    add_comic()
  File "AddToFunnies.py", line 10, in add_comic
    comic = urllib.urlopen(comic_url).read()
  File "C:\Python27\lib\urllib.py", line 84, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 356, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 369, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 651, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "C:\Python27\lib\urllib.py", line 632, in http_error_302
    data)
  File "C:\Python27\lib\urllib.py", line 647, in redirect_internal
    return self.open(newurl)
  File "C:\Python27\lib\urllib.py", line 205, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 435, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 940, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 803, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 755, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1156, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "C:\Python27\lib\ssl.py", line 342, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 121, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 281, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:499: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by NoahWhite1115** [comment]
Other notes: 
Python version 2.7.15 used here. Linux version may be different (lower possibly) preventing the issue.

**Comment by NoahWhite1115** [comment]
My Linux machine is using Python 2.7.14. Urllib on this machine is urllib3, version 1.22

**Comment by NoahWhite1115** [comment]
The issues seems to have gone away after adding urllib3. However, it would be a good idea to explicitly state in the imports that urllib3 is used.
